// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versta_test_project.Data;

#nullable disable

namespace Versta_test_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("Versta_test_project.Models.OrderModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("collectionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("packageWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("recipientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("recipientCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senderCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
